### PR TITLE
Check for the MySQL open files limit

### PR DESCRIPTION
**Pull request by tomassedovic**
https://access.redhat.com/solutions/1598733

This checks whether the `open-files-limit` limit passed to MySQL/MariaDB is greater or equal to 16384 (the recommended value).

### CODE REVIEW

**Comment by mandre** [comment]
You can get the open-file-limit much more reliably by querying mysql server at runtime:

select @@global.open_files_limit;

**Comment by tomassedovic** [comment]
Ooh, nice! I've updated the pull request.

**Comment by mandre** [comment]
It can be useful to add the current value for open_files_limit to the error message.

Looks a lot better now :+1:

**Comment by tomassedovic** [comment]
Good point. Added.

**Comment by mandre** [comment]
Actually, I realized there is an ansible module to do just that: http://docs.ansible.com/ansible/mysql_variables_module.html. It adds a dependency on MySQL-python but it should already be satisfied on the controller nodes.

Would you mind changing once again?

Also, I realized you used the shell module while you should really have used the command module. The shell module should be avoided when possible.

**Comment by tomassedovic** [comment]
All right, this should be fixed up & rebased now.

I was originally using shell pipes which don't work with the command module, but you're right that when that was removed, I should have switched to command.

**Pull request merged**
