### PR TITLE
Browbeat Controller Checks

### PR DESCRIPTION
**Pull request by jtaleric**
This is the initial work to see what we need to do to add the Browbeat Checks to Clapper/TripleO Validations.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Thanks!

It looks good, but when I run the playbook, it aborts the tasks after the first failure it encounters. So e.g. if the "Get rabbitmq status" task fails, nothing else will be run.

I can't think of a way to solve this while keeping the validations in one file -- I tried adding "ignore_errors: true" which will get through the whole play, but the play will be treated as successful.

Do you know of something that could solve this? It's not a deal breaker if we can't , but it would be nicer to the end users.

**Comment by tomassedovic** [comment]
@mandre: any thoughts?

**Comment by jtaleric** [comment]
Yup... This is what I did in the past, simply ignore_errors: true, then I check the values after the fact using a template. However, that might not fit your model.

**Comment by tomassedovic** [comment]
@jtaleric yea so the problem with that is we can't (programaticaly) tell when a failure is a legitimate error and when it should be ignored. I guess we could just forbid ignore_errors in "normal" validations and just treat all ignored failures as legitimate.

Here's another idea: we could keep the file to make contributions easier and one of the maintainers (e.g. me) could split these up into multiple files later on. Would that work for you?

**Comment by jtaleric** [comment]
@tomassedovic I am good with breaking each check into its own files... I do recommend we at least house these into their own directory, thoughts?

**Comment by tomassedovic** [comment]
@jtaleric we'll have to update the API to pick them up (it just checks the validations directory for yaml files right now), but I think that should be fine.

@mandre is working on the API -- what do you think, Martin?

**Comment by mandre** [comment]
@jtaleric: Agreed. We should start organizing validations in separate folders otherwise it will quickly become unmanageable. I'm less sure about how to organize the files. Some of your checks are duplicate of existing validations. What do you think of grouping validations per service or node (mysql, rabbitmq, undercloud hardware, etc.)?

@tomassedovic: I'm not too concerned for the API counterpart, we can always change the way it's consuming the validations if we realize the structure of the repository doesn't fit and we do a bit or reorganization.

**Comment by jtaleric** [comment]
@mandre Agreed, there are some duplicates. It would be good to create a digest of what already exists, so the user doesn't have to open each individual file. Maybe we could generate some sort of report (html,text,??) that tells the user, here are the checks for a given role. 

I do like the idea of grouping validations per service, or s/node/role. That way if a user wants to add a validation for mysql it is obvious where they add it.

**Comment by mandre** [comment]
@jtaleric: so there is already a digest of available validations (sort of) in the form of a [README](https://github.com/rthallisey/clapper/blob/master/ansible-tests/validations/README.md). Since we're targeting the tripleo-validations repo under the openstack organization I was thinking we could make use of OpenStack infra and run a doc job that parse the validations and publish on docs.openstack.org.

**Comment by tomassedovic** [comment]
ooh I love the idea of autogenerating the list of validations & their description.

**Comment by jtaleric** [comment]
So, would we want something like :

```
- messaging
- database
- load_balancer
- nova
- neutron
- glance
- hardware-validations
```

**Comment by mandre** [comment]
@jtaleric looks like a good start. Probably this list is going to evolve a lot over time as we find better categories for the validations (I'm thinking for example about validations that could potentially be in many of the above categories like [checking openstack endpoints](https://github.com/rthallisey/clapper/blob/master/ansible-tests/validations/check_openstack_endpoints.yaml)) but that shouldn't be a problem for the mistral validations runner if we keep unique filenames across subdirs.

**Pull request closed without merging**
